name: datawhys-nlp
channels:
  - pytorch
  - plotly
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2
  - cupy
  - gensim=3.8.3
  - ipympl
  - jupyterlab=1.2
  - matplotlib
  - neuralcoref
  - nltk=3.4.5
  - nodejs=16
  - numpy
  - openssl<3
  - pandas
  - pip
  - plotly
  - ptvsd
  - pyldavis
  - python=3.7
  - pytorch 
  - scikit-learn
  - spacy-transformers
  - spacy=3
  - torchvision
  - torchaudio
  - xeus=0.23
  - xeus-python

