name: datawhys-nlp
channels:
  - conda-forge
  - defaults
  - plotly
  - pytorch
dependencies:
  - python=3.7
  - xeus-python=0.6.8
  - jupyterlab=1.2
  - ptvsd
  - nodejs=16
  - openssl<3
  - plotly
  - pip
  - pandas
  - matplotlib
  - scikit-learn
  - ipympl
  - numpy
  - nltk=3.4.5
  - scikit-learn
  - spacy=3
  - spacy-transformers
  - neuralcoref
  - pytorch 
  - gensim
  - pyldavis
